# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 5.4
  - 5.5
  - hhvm

matrix:
  allow_failures:
    -php: hhvm

# Set environment variables
env:
  - DB_HOST=localhost
  - DB_NAME=madison_grunt_test 

# Commands to be run before your environment runs.
before_script:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - grunt install
  - "mysql -e 'create database madison_grunt_test;'"

# Commands you want to run that will verify your build.
script: grunt test_unit

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always