# This is an example credential file
# 
# The raw credentials are separated from the config file in the case that 
# a change is needed in the database config file

database: madison_database
username: username
password: password

admin_email: admin@example.com
admin_fname: First
admin_lname: Last
admin_password: password