dry-run: null
hookfiles: null
language: php
sandbox: false
server: TESTING=true DB_CONNECTION=mysql_testing php artisan serve --host 0.0.0.0 --port 8999
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: cli
output: []
header: []
sorted: false
user: null
inline-errors: false
details: false
method: []
color: true
level: info
timestamp: false
silent: false
path: []
blueprint: blueprint/madison.apib
endpoint: 'http://localhost:8999'
